### ISSUE TITLE
PREXT Configuration Error

### ISSUE THREAD

**Issue by Humi-COMSATS** [karim-emara/PREXT#1]
Hi, I am MS student working on location privacy scheme in VANETs. I have installed SUMO-0.25.0, Omnet++ 5.0and Veins-4.4 on Ubuntu 16.04 LTS. I am adding PREXT module in veins project as described in [1]. When rebuild veins project it displays some warnings on paths specified in 'Paths & Symbols' section. However, I cross checked it multiple times and there is no mistake in defining paths. When I try to run pextdemo example, error displays stating ' Error in Module (omnetpp::cModule) PrivScenario (id=1) during network setup: Class "VehicleTracker" not found-perhaps its code was not linked in, or the class wasn't registered with Register-Class(), or in the case of modules and channels, with Define-module() | Define-Channel().
Please help me. I am stucked on Prext module configuration for 3 weeks. 
Thanks.
Regards,
Humi

[1] https://github.com/karim-emara/PREXT/blob/master/README.md

**Comment by karim-emara** [comment]
Hi, 
It seems that the tracker library is not accessible or not well-configured. Please double check these two steps:
1- Select "Library Paths" tab -> add the following path "~/veins-veins-4.4/veins/src/veins/modules/Prext/lib"
2- On the left tree, Expand "OMNET++" -> Select Makemake:
On the right view, Expand "veins: custom makefile" -> Select "src: makemake..." -> On the right, click on "Options..." button under "Makemake" radio button. On the pop-up dialog, Select "Link" tab -> press "More>>" -> add a library in the *first* list "Additional libraries to link with: (-l option)" by clicking on the small button just above the list -> In the pop-up dialog, write "NNPDA", then click "OK"

Note: write paths without quotes and preferably use "Browse.." button to navigate to the aimed directory. 

EDIT:
I have added some screenshots for PREXT configuration in the Readme [1]. They usually works with on ubuntu without problems. 
You can also give a try to the virtual machine in which omnet, veins, sumo and PREXT are installed and working perfectly. You can find the link in the Readme [1] as well

[1] https://github.com/karim-emara/PREXT/blob/master/README.md
