### ISSUE TITLE
Veins , Private scheme , please help me 

### ISSUE THREAD

**Issue by Izdhar** [karim-emara/PREXT#10]

**Comment by Izdhar** [comment]
What is the encryption algorithm used in the prext schemes ?
2- How can I get car access rates? 
![1](https://user-images.githubusercontent.com/39618668/50377648-13b0dc00-0632-11e9-9eb5-d1763eb67043.PNG)
![2](https://user-images.githubusercontent.com/39618668/50377649-13b0dc00-0632-11e9-994f-7a12dde63d9a.PNG)
![3](https://user-images.githubusercontent.com/39618668/50377650-14497280-0632-11e9-9af1-49eab3431381.PNG)
 


How did you calculate the traces, is there a mathematical relationship relied upon in the account?

What is meant by (obstacle shadowing) and what do you mean by (cut)??
please help me ....
I read your article about PREXT ....

**Comment by karim-emara** [comment]
There is no actual encryption done in prext. Only isEncrypted is set in the WAVEBeacon message to indicate the message is encrypted.

Arrival rates were specified as parameters while the SUMO route files are generated. Thus, it is not possible to change them from veins or prext.

Traces are calculated by counting all unique vehicle routes occurred in the route file.

Shadowing concerns how the wireless signal is obstructed by buildings and obstacles. Cut means object.
