### ISSUE TITLE
prext-run error

### ISSUE THREAD

**Issue by Sweetning** [karim-emara/PREXT#11]
hello,emara
i am a student and learn about location privacy recently.
i have download the preconfigured virtual machine ,it can build correctly but when i click run button it dosen't work well.
the error as follow:
<!> Error in module (Veins::TraCIScenarioManagerLaunchd) PrivScenario.manager (id=6) at event #1, t=0: Model error: TraCI server "" reports API version 881918208, which is unsupported. We recommend using SUMO 0.25.0..
and i can run the demo veins project but it doesn't  display map.
look forward to hearing from you.,thank you very much!

**Comment by karim-emara** [comment]
There is a configuration mistake in the .bash_rc file.
change the last line starting with "export SUMO_HOME = ..." to 
export SUMO_HOME=$HOME/src/sumo-0.25.0

please ensure that you run the SUMO in the background before clicking the run button in OMNET by running this command in command terminal (Ctrl+Alt+T):
~/src/veins-veins-4.4/sumo-launchd.py -vv -c ~/src/sumo-0.25.0/bin/sumo
