### ISSUE TITLE
BaseLayer.h not found

### ISSUE THREAD

**Issue by sarahalshareeda** [karim-emara/PREXT#2]
hi karim,
I am trying to install prext and when i make veins it says:
BaseLayer.h is not found when i gcc prext/base/baseprivlayer.h,
could you please help with this?

**Comment by karim-emara** [comment]
Hi Sarah,
please ensure that you have added "/veins/src/veins/modules/Prext/include" to the include paths
In the veins configuration, "C/C++ General"->"Paths and Symbols" tab: On the right view, Select "Includes" tab"/"GNU C++".
I have added some images of the configuration dialogs to the Readme. They may help. 

please let me know if you resolved this issue.

Best,
Karim

**Comment by sarahalshareeda** [comment]
solved Karim,
Thanks, I just changed the veins folder name,
Now for another problem the CAPS.cc file under Prext/schemes folder.
I receive this error:
conversion from 'omnetpp::cPar' to 'int64_t' (aka 'long long') is ambiguous.
i think it is related with the simtime constructors support in omnetpp version 5,
I'm running on windows 7 enterprise, 
any idea about this?
Sarah

**Comment by karim-emara** [comment]
Great, then I will close the issue.
For conversion issue, it seems that implicit casting is not working in windows. You can overcome this by using longValue, doubleValue, or boolValue member functions of cPar.
e.g., 
```
minPsynmLifetime = SimTime(par("minPsynmLifetime").longValue(), SimTimeUnit::SIMTIME_S);
```
I will try to change all implicit cPar casting to explicit ones and push that to github soon.

Please let me know if you are successful in compiling Prext on windows. You will be the first :)

-- Karim
